---
spring:
  config.activate.on-profile: cloud
cds:
  datasource:
    auto-config.enabled: false
  messaging:
    services:
      - name: "taskmanager-events"
        kind: "enterprise-messaging"
        queue: 
        - name: "StudentEnrolled"
