---
spring:
  config.activate.on-profile: cloud
server:
  port: 9090
cds:
  datasource:
    auto-config.enabled: false
  messaging:
    services:
      - name: "taskmanager-events"
        kind: "enterprise-messaging"
